"""init

Revision ID: c1f792c094da
Revises: 
Create Date: 2026-03-21 14:06:02.361933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f792c094da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_journal',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.Column('action_code', sa.String(length=30), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=False),
    sa.Column('target_role', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_journal_trace_id'), 'operation_journal', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_journal_trace_id'), table_name='operation_journal')
    op.drop_table('operation_journal')
    # ### end Alembic commands ###
